[workspace]
members = ["core", "cli"]
resolver = "2"

[workspace.package]
version = "0.2.0"
edition = "2021"

[workspace.lints.clippy]
unwrap_used = "deny"
expect_used = "warn"
todo = "deny"
dbg_macro = "warn"
